### ISSUE TITLE
Make a logo and a favicon

### ISSUE THREAD

**Issue by spresnac** [spresnac/logcrawler-client#17]
I am quite bad with graphics, so it would be nice to have someone create a logo and a favicon for logcrawler.de
Feel absolutely free, i have absolutely no idea how it should look like!

**Comment by aman05382** [comment]
ok i will do this please assign me

**Comment by spresnac** [comment]
> ok i will do this please assign me

Nice, let's rock it :D

**Comment by aman05382** [comment]
**[I have done it please check it and allow me in Hacktoberfest](https://github.com/spresnac/logcrawler-client/pull/18)**

**Comment by spresnac** [comment]
> **[I have done it please check it and allow me in Hacktoberfest](https://github.com/spresnac/logcrawler-client/pull/18)**

Hi,
sry, i cannot accept this PR for this is just a "stolen" image with a text under it, see here:

https://www.google.com/search?tbs=sbi:AMhZZiuXv0sMQAnpAjCFyodhUeOj5lRV2w6LLle-I4WBREXycV2klck1Ckvi2e_1w3OrL0FVMlsmN2UCc90a5RKkaUWZFEn1l3QJihKMZIaXp-4ZLQjZfBb88wOPyA_1UfVVmSoHLizG1w-cNB85fppvYv5NQFdrTx-ZpT0vfKTfB4tep23uWrDYGYTSGG3w6tJgSQB7gH1-R-FW_1kZZw2RheoBDjfk7tUS4VFmu6oNSvARob3WK_1dUH-hdLlHTfKAFSn9hLhbYmsbk7_16FUYtym49lUSUvLu2lLUokJFlLggsa2j0Zvef0vWFgzbGveQDgIxVIchlRR-M-HqApreq1kdXYWHmPWZsQQ&hl=de

The intention was to get some unique image for the service, not a pr just to fullfill the hacktoberfest ;)

Feel free to contribute with a real image fitting the service.

**Comment by aman05382** [comment]
Sir, I have taken the image from free website. this website offers free vectors so anyone can use it for there commercial and personal projects

**Comment by spresnac** [comment]
> Sir, I have taken the image from free website. this website offers free vectors so anyone can use it for there commercial and personal projects

Ok, this is good and no problem, but i have to review that site where you got the image from. Can you provide the URL?

**Comment by aman05382** [comment]
https://www.freepik.com/free-vector/programmers-concept-with-flat-design_2488094.htm#page=1&query=programming&position=1

Sir check this My Work is genuine

**Comment by spresnac** [comment]
> https://www.freepik.com/free-vector/programmers-concept-with-flat-design_2488094.htm#page=1&query=programming&position=1
> 
> Sir check this My Work is genuine

Hej. Okay, didn't see that. So, i need to add a link to that side, i do not think, this is a problem. But some questions: Can you please make the logo either transparent or with a white Background, so it fit's better to the website? And can you please remove the writing, that can be done with html overlay. I just need that logo. And maybe the favicon more "lookable"? Can describe it better, but i cannot "see" what the favicon stands for, when adding it and look in the browser to my tab. Hope, you understand, what i mean ;)

**Comment by aman05382** [comment]
ok : please wait for me i Will make this time Fully Genuie logo

**Comment by spresnac** [comment]
thanks
